version: '3.8'

volumes:
    db_data: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: gdrive_local_django
    container_name: django
    depends_on:
      - db
      - mailhog
      - solr
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.mysql
    ports:
      - "8000:8000"
    command: /start

  db:
    image: mysql:8.0
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    volumes:
       - db_data:/var/lib/mysql
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306  # cannot change this port to other number
      - MYSQL_DATABASE=gdrive # name you want for the database
      - MYSQL_USER=root # change to whatever username you want
      - MYSQL_PASSWORD=gdrive_pass #change to the password you want for user
      - MYSQL_ROOT_PASSWORD=gdrive_pass #change to good root password

  docs:
    image: gdrive_local_docs
    container_name: docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./gdrive:/app/gdrive:z
    ports:
      - "7000:7000"

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: mailhog
    ports:
      - "8025:8025"

  solr:
    image: solr:8.6.3-slim
    container_name: solr
    restart: always
    ports:
      - "8983:8983"
    volumes:
      - ./compose/local/solr/drive:/opt/solr/server/solr/configsets/drive:rw
    entrypoint:
    - bash
    - "-c"
    - "precreate-core drive /opt/solr/server/solr/configsets/drive ;\
       exec solr -f"
    environment:
      - SOLR_HEAP=500m
