version: '3'

volumes:
  db_data: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: gdrive_production_django
    depends_on:
      - solr
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.mysql
    command: /start

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: gdrive_production_nginx
    env_file: .env
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    depends_on:
      - django
    links:
      - django

  solr:
    image: solr:6.6.6-slim
    container_name: solr
    restart: always
    ports:
      - "8983:8983"
    volumes:
      - ./compose/local/solr/drive:/opt/solr/server/solr/configsets/drive:rw
    entrypoint:
    - bash
    - "-c"
    - "precreate-core drive /opt/solr/server/solr/configsets/drive ;\
       exec solr -f"
    environment:
      - SOLR_HEAP=500m
