# Generated by Django 3.1.2 on 2020-10-27 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gfile',
            options={'ordering': ['-created']},
        ),
    ]
